#!/bin/bash
# Catching incorrect params for set up command
if [[ $# -ne 1 ]];
then
 	echo "[$(date +'%Y-%m-%d %H:%M:%S')] CRITCAL ERROR: incorrect params in $(pwd)/setup_big_tech.sh (4)" >> scripts.log
	exit 4
fi

CONTAINER_NAME=$1

sudo lxc-attach -n "$CONTAINER_NAME" -- bash -c "mkdir Hardware Website Customer_Services; cd Hardware; mkdir Home_Devices; cd ../Website; mkdir Resources; cd ../Customer_Services; mkdir Guides Assistance"

sleep 2

cp /home/student/test/draft_honey/big_device_data.csv /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Hardware/Home_Devices/device_data.csv

cp /home/student/test/draft_honey/big_userprefs.xls /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Website/Resources/userprefs.xls

cp /home/student/test/draft_honey/big_login_customer.csv /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Customer_Services/Assistance/login_customer.csv

echo "[$(date +'%Y-%m-%d %H:%M:%S')] SUCCESS: $(pwd)/setup_big_tech.sh completed (0)" >> scripts.log
exit 0
