#!/bin/bash
# Catching incorrect params for set up command
if [[ $# -ne 1 ]];
then
	echo "[$(date +'%Y-%m-%d %H:%M:%S')] CRITICAL ERROR: incorrect params in $(pwd)/setup_little_fin.sh (6)" >> scripts.log
	exit 6
fi

CONTAINER_NAME=$1

sudo lxc-attach -n "$CONTAINER_NAME" -- bash -c "mkdir Customer_Service Services Activity; cd Customer_Service; mkdir Resources; cd ../Services; mkdir Credit_Card Retirement; cd ../Activity; mkdir Transfers"

sleep 2

cp /home/student/test/draft_honey/little_bankacc_customer.csv /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Customer_Service/Resources/bankacc_customer.csv

cp /home/student/test/draft_honey/little_creditcard_info.csv /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Services/Credit_Card/creditcard_info.csv

cp /home/student/test/draft_honey/little_moneytransfer_hist.xls /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Activity/Transfers/moneytransfer_hist.xls

echo "[$(date +'%Y-%m-%d %H:%M:%S')] SUCCESS: $(pwd)/setup_little_fin.sh completed (0)" >> scripts.log
exit 0
