#!/bin/bash
# Catching incorrect params for set up command
if [[ $# -ne 1 ]];
then
	echo "[$(date +'%Y-%m-%d %H:%M:%S')] CRITICAL ERROR: incorrect params in $(pwd)/setup_big_med.sh (3)" >> scripts.log
	exit 3
fi

CONTAINER_NAME=$1

sudo lxc-attach -n "$CONTAINER_NAME" -- bash -c "mkdir Patients General Public; cd Patients; mkdir Data; cd ../General; mkdir Historical; cd ../Public; mkdir Information Documents"

sleep 2

cp /home/student/test/draft_honey/big_patient_files.csv /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Patients/Data/patient_files.csv

cp /home/student/test/draft_honey/big_hospital_hist.xls /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/General/Historical/hospital_hist.xls

cp /home/student/test/draft_honey/big_insurance.csv /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Public/Documents/insurance.csv

echo "[$(date +'%Y-%m-%d %H:%M:%S')] SUCCESS: $(pwd)/setup_big_med.sh completed (0)" >> scripts.log
exit 0
