#!/bin/bash
# Catching incorrect params for set up command
if [[ $# -ne 1 ]];
then
 	echo "[$(date +'%Y-%m-%d %H:%M:%S')] CRITICAL ERROR: incorrect params in $(pwd)/setup_little_med.sh (8)" >> scripts.log
	exit 8
fi

CONTAINER_NAME=$1

sudo lxc-attach -n "$CONTAINER_NAME" -- bash -c "mkdir Patients General Public; cd Patients; mkdir Data; cd ../General; mkdir Historical; cd ../Public; mkdir Information Documents"

sleep 5

cp /home/student/test/draft_honey/little_patient_files.csv /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Patients/Data/patient_files.csv

cp /home/student/test/draft_honey/little_hospital_hist.xls /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/General/Historical/hospital_hist.xls

cp /home/student/test/draft_honey/little_insurance.csv /var/lib/lxc/"$CONTAINER_NAME"/rootfs/root/Public/Information/insurance.csv

echo "[$(date +'%Y-%m-%d %H:%M:%S')] SUCCESS: $(pwd)/setup_little_med.sh completed (0)" >> scripts.log
exit 0
